package com.example.subtitleoverlay;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.graphics.Color;import android.view.*;import android.widget.*;
public class MainActivity extends Activity{
 static final int PICK=10;Uri uri;TextView status;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(32,32,32,32);TextView h=new TextView(this);h.setText("Subtitle Overlay MVP v0.1");h.setTextSize(24);h.setTextColor(Color.BLACK);l.addView(h);status=new TextView(this);status.setText("Select an SRT file.");status.setPadding(0,20,0,20);l.addView(status);Button p=btn("Select SRT");p.setOnClickListener(v->pick());l.addView(p);Button o=btn("Allow overlay");o.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName()))));l.addView(o);Button a=btn("Enable Accessibility sync");a.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));l.addView(a);Button s=btn("START OVERLAY");s.setOnClickListener(v->start());l.addView(s);Button stop=btn("STOP OVERLAY");stop.setOnClickListener(v->stopService(new Intent(this,OverlayService.class)));l.addView(stop);TextView info=new TextView(this);info.setText("The MVP displays your SRT above any app. Accessibility sync is experimental; if Brave does not expose playback time, use the +/- sync buttons.");info.setPadding(0,20,0,0);l.addView(info);setContentView(l);}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null){uri=d.getData();try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}status.setText("Selected: "+uri.getLastPathSegment());}}
 void start(){if(uri==null){Toast.makeText(this,"Select an SRT first",Toast.LENGTH_SHORT).show();return;}if(!Settings.canDrawOverlays(this)){Toast.makeText(this,"Allow overlay first",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(this,OverlayService.class).setAction(OverlayService.START).putExtra(OverlayService.URI,uri.toString());if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);status.setText("Overlay running");}
}
