package com.example.subtitleoverlay;
import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
public class OverlayService extends Service{
 public static final String START="START",URI="uri";static volatile OverlayService instance;WindowManager wm;TextView sub;LinearLayout ctl;List<SrtCue> cues=new ArrayList<>();Handler h=new Handler(Looper.getMainLooper());long external=-1,offset=0,base=0,start;boolean run=true;
 public static void setExternal(long ms){if(instance!=null)instance.external=ms;}
 public void onCreate(){super.onCreate();instance=this;NotificationChannel c=new NotificationChannel("sub","Subtitle Overlay",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);startForeground(9,new Notification.Builder(this,"sub").setContentTitle("Subtitle Overlay running").setSmallIcon(android.R.drawable.ic_media_play).setOngoing(true).build());}
 public int onStartCommand(Intent i,int f,int id){if(i!=null&&START.equals(i.getAction()))try(InputStream in=getContentResolver().openInputStream(Uri.parse(i.getStringExtra(URI)))){cues=SrtParser.parse(in);build();}catch(Exception e){Toast.makeText(this,"SRT error: "+e.getMessage(),Toast.LENGTH_LONG).show();}return START_STICKY;}
 void build(){remove();wm=(WindowManager)getSystemService(WINDOW_SERVICE);sub=new TextView(this);sub.setTextColor(Color.WHITE);sub.setTextSize(24);sub.setGravity(Gravity.CENTER);sub.setTextDirection(View.TEXT_DIRECTION_ANY_RTL);sub.setShadowLayer(8,0,2,Color.BLACK);sub.setPadding(20,8,20,8);WindowManager.LayoutParams p=new WindowManager.LayoutParams(-1,-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);p.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;p.y=90;wm.addView(sub,p);
 ctl=new LinearLayout(this);ctl.setOrientation(LinearLayout.HORIZONTAL);String[] ss={"-0.5s","+0.5s","Pause","✕"};for(String x:ss){Button b=new Button(this);b.setText(x);b.setTextSize(11);ctl.addView(b);if(x.startsWith("-"))b.setOnClickListener(v->offset-=500);else if(x.startsWith("+"))b.setOnClickListener(v->offset+=500);else if(x.equals("Pause"))b.setOnClickListener(v->{run=!run;if(run)start=SystemClock.uptimeMillis();b.setText(run?"Pause":"Play");});else b.setOnClickListener(v->stopSelf());}WindowManager.LayoutParams q=new WindowManager.LayoutParams(-2,-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,PixelFormat.TRANSLUCENT);q.gravity=Gravity.TOP|Gravity.END;q.x=10;q.y=30;wm.addView(ctl,q);start=SystemClock.uptimeMillis();h.post(tick);}
 Runnable tick=new Runnable(){public void run(){if(sub==null)return;long pos=external>=0?external+offset:(run?base+SystemClock.uptimeMillis()-start:base)+offset;SrtCue found=null;for(SrtCue c:cues){if(pos>=c.startMs&&pos<=c.endMs){found=c;break;}if(c.startMs>pos)break;}sub.setText(found==null?"":found.text);h.postDelayed(this,80);}};
 void remove(){if(wm==null)return;try{if(sub!=null)wm.removeView(sub);}catch(Exception ignored){}try{if(ctl!=null)wm.removeView(ctl);}catch(Exception ignored){}sub=null;ctl=null;}
 public void onDestroy(){h.removeCallbacksAndMessages(null);remove();instance=null;super.onDestroy();}public IBinder onBind(Intent i){return null;}
}
